# Generated by Django 5.0.3 on 2026-09-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('avg_temperature_c', models.FloatField()),
                ('solar_radiation_wm2', models.FloatField()),
                ('wind_speed_ms', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InsulationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('r_value_per_inch', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thermal_conductivity', models.FloatField(help_text='W/(m·K)')),
                ('density', models.FloatField(help_text='kg/m³')),
                ('specific_heat', models.FloatField(help_text='J/(kg·K)')),
            ],
        ),
        migrations.CreateModel(
            name='ShelterDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shape', models.CharField(choices=[('rectangular', 'Rectangular'), ('a_frame', 'A-Frame'), ('dome', 'Dome')], default='rectangular', max_length=20)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('orientation', models.FloatField(help_text='Degrees from North')),
                ('insulation_thickness', models.FloatField(default=0.0)),
                ('window_area', models.FloatField(default=0.0)),
                ('door_area', models.FloatField(default=0.0)),
                ('insulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thermal.insulationmaterial')),
                ('roof_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roof_designs', to='thermal.material')),
                ('wall_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wall_designs', to='thermal.material')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thermal.climatedata')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thermal.shelterdesign')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indoor_temperature_c', models.FloatField()),
                ('heat_loss_w', models.FloatField()),
                ('solar_heat_gain_w', models.FloatField()),
                ('heating_requirement_kwh', models.FloatField()),
                ('thermal_comfort_score', models.FloatField(help_text='0-100 score')),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='thermal.simulation')),
            ],
        ),
    ]
