def estimate_indoor_temperature(t_out, total_solar_gain, total_ua, thermal_mass):
    """
    Estimates indoor temperature using a simplified thermal balance model.

    The model considers:
    - Outdoor temperature
    - Solar heat gain
    - Internal heat gain
    - Overall heat transfer coefficient (UA)
    - Thermal mass of the shelter

    This is a simplified engineering model, not a CFD simulation.
    """

    if total_ua <= 0:
        return t_out

    # Internal heat generated by occupants/equipment
    internal_gains = 200.0

    # Total heat entering the shelter
    total_gains = total_solar_gain + internal_gains

    # Raw temperature rise caused by heat gains
    raw_delta_t = total_gains / total_ua

    # Thermal mass reduces rapid temperature changes
    if thermal_mass <= 0:
        damping_factor = 1.0
    else:
        damping_factor = 1.0 / (1.0 + thermal_mass / 1_000_000.0)

    # Keep the damping factor within a practical range
    damping_factor = max(0.25, min(damping_factor, 0.85))

    damped_delta_t = raw_delta_t * damping_factor

    # Prevent the simplified model from producing extreme temperatures.
    # Maximum modeled rise above outdoor temperature = 8°C.
    damped_delta_t = min(damped_delta_t, 8.0)

    # Allow a small reduction below outdoor temperature
    # when there is very little solar/internal gain.
    damped_delta_t = max(damped_delta_t, -3.0)

    t_in = t_out + damped_delta_t

    return round(t_in, 2)